// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMTPterodactyl.Infrastructure.Database;

#nullable disable

namespace SMTPterodactyl.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120085620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("SMTPterodactyl.Core.Channels.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasDiscriminator().HasValue("Channel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SMTPterodactyl.Core.Channels.TelegramBotConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BotToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TelegramBotConfigurations");
                });

            modelBuilder.Entity("SMTPterodactyl.Infrastructure.Persistence.FlowChannelRow", b =>
                {
                    b.Property<Guid>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("TEXT");

                    b.HasKey("FlowId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("FlowChannels");
                });

            modelBuilder.Entity("SMTPterodactyl.Infrastructure.Persistence.FlowRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("SMTPterodactyl.Core.Channels.ConsoleChannel", b =>
                {
                    b.HasBaseType("SMTPterodactyl.Core.Channels.Channel");

                    b.HasDiscriminator().HasValue("ConsoleChannel");
                });

            modelBuilder.Entity("SMTPterodactyl.Core.Channels.FileChannel", b =>
                {
                    b.HasBaseType("SMTPterodactyl.Core.Channels.Channel");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("FileChannel");
                });

            modelBuilder.Entity("SMTPterodactyl.Core.Channels.TelegramChannel", b =>
                {
                    b.HasBaseType("SMTPterodactyl.Core.Channels.Channel");

                    b.Property<Guid>("BotConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("BotConfigurationId");

                    b.HasDiscriminator().HasValue("TelegramChannel");
                });

            modelBuilder.Entity("SMTPterodactyl.Infrastructure.Persistence.FlowChannelRow", b =>
                {
                    b.HasOne("SMTPterodactyl.Core.Channels.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMTPterodactyl.Infrastructure.Persistence.FlowRow", null)
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMTPterodactyl.Core.Channels.TelegramChannel", b =>
                {
                    b.HasOne("SMTPterodactyl.Core.Channels.TelegramBotConfiguration", "BotConfiguration")
                        .WithMany()
                        .HasForeignKey("BotConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BotConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
