// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMTPterodactyl.Infrastructure.Database;

#nullable disable

namespace SMTPterodactyl.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ChannelFlow", b =>
                {
                    b.Property<Guid>("ChannelsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelsId", "FlowsId");

                    b.HasIndex("FlowsId");

                    b.ToTable("ChannelFlow");
                });

            modelBuilder.Entity("SMTPterodactyl.Core.Entities.Channels.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasDiscriminator().HasValue("Channel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SMTPterodactyl.Core.Entities.Flow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("SMTPterodactyl.Core.Entities.Channels.ConsoleChannel", b =>
                {
                    b.HasBaseType("SMTPterodactyl.Core.Entities.Channels.Channel");

                    b.HasDiscriminator().HasValue("ConsoleChannel");
                });

            modelBuilder.Entity("SMTPterodactyl.Core.Entities.Channels.FileChannel", b =>
                {
                    b.HasBaseType("SMTPterodactyl.Core.Entities.Channels.Channel");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("FileChannel");
                });

            modelBuilder.Entity("SMTPterodactyl.Core.Entities.Channels.TelegramChannel", b =>
                {
                    b.HasBaseType("SMTPterodactyl.Core.Entities.Channels.Channel");

                    b.Property<string>("BotToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TelegramChannel");
                });

            modelBuilder.Entity("ChannelFlow", b =>
                {
                    b.HasOne("SMTPterodactyl.Core.Entities.Channels.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMTPterodactyl.Core.Entities.Flow", null)
                        .WithMany()
                        .HasForeignKey("FlowsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
